/* Untyped file generated by genType. */

import * as JavaScriptApiLayoutBS from './JavaScriptApiLayout.bs';

export const Docs_make = JavaScriptApiLayoutBS.Docs.make;

export const Prose_make = JavaScriptApiLayoutBS.Prose.make;

export const Docs = JavaScriptApiLayoutBS.Docs

export const Prose = JavaScriptApiLayoutBS.Prose
