/* Untyped file generated by genType. */

import * as SidebarLayoutBS from './SidebarLayout.bs';

export const Docs_make = SidebarLayoutBS.Docs.make;

export const Prose_make = SidebarLayoutBS.Prose.make;

export const Docs = SidebarLayoutBS.Docs

export const Prose = SidebarLayoutBS.Prose
